---
title: "Cars Analysis"
author: "Ivan Iakimov"
date: '1 June 2018'
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r}
library(plotly)
```

## Miles per gallon by weight

Hover your mouse over a data point to see name of the corresponding car.

```{r}
x <- list(title = "Weight (1000 lbs)")

y <- list(title = "Miles per gallon")

plot_ly(mtcars, 
        x = ~wt, 
        y = ~mpg, 
        color = ~factor(paste(cyl, " cylinders")),
        text = ~rownames(mtcars),
        type = "scatter"
        ) %>%
    layout(xaxis = x, yaxis = y)
```

## 1/4 mile time distribution

```{r}
x <- list(title = "1/4 mile time")

y <- list(title = "")

plot_ly(mtcars, 
        x = ~qsec, 
        text = ~rownames(mtcars),
        type = "histogram"
        ) %>%
    layout(xaxis = x, yaxis = y)
```

## Miles per gallon by transmission type

```{r}
x <- list(title = "Type of transmission")

y <- list(title = "Miles per gallon")

plot_ly(mtcars, 
        y = ~qsec, 
        color = ~factor(ifelse(am == 0, "Auto", "Manual")),
        type = "box"
        ) %>%
    layout(xaxis = x, yaxis = y)
```
